#### 1)Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of (N - i - 1). 
```
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

```

In [43]:
import numpy as np

In [44]:
def matPower(inputValue, n, increasing=False):
    
    if not increasing:
        outMat = np.array([x**(n-i-1) for x in inputValue for i in range(n)]).reshape(inputValue.size,n)
    elif increasing:
        outMat = np.array([x**i for x in inputValue for i in range(n)]).reshape(inputValue.size,n)
    return outMat

In [45]:
inputArray = np.array([1,2,3,4,5])
print('-'*20)
print('Decreased Power')
print('-'*20)
print(matPower(inputArray,3,False))
print('-'*20)
print('Increased Power')
print('-'*20)
print(matPower(inputArray,3,True))

--------------------
Decreased Power
--------------------
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
--------------------
Increased Power
--------------------
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


#### 2) Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [46]:
def movingAverage(a, n=3) :
    result = np.cumsum(a, dtype=float)
    result[n:] = result[n:] - result[:-n]
    return result[n - 1:] / n

In [47]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(movingAverage(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
